apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: watch-app
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.15.1
          args:
            - "--config.my-cnf=/etc/mysql-exporter/my.cnf"
          ports:
            - name: metrics
              containerPort: 9104
          volumeMounts:
            - name: config
              mountPath: /etc/mysql-exporter
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: mysql-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: watch-app
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104